#spring:
#  application:
#    name: demo
#  security:
#    user:
#      name: nijunyang
#      password: 123456
#server:
#  compression:
#    enabled: false
#    mime-types: text/html,text/xml,text/plain,application/json,application/xml
#    min-response-size: 1KB

# \u8BBE\u7F6E\u66B4\u9732\u6240\u6709\u7AEF\u70B9
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  security:
        #    enabled: false