spring:
  application:
    name: demo
  security:
    user:
      name: nijunyang
      password: 123456
#server:
#  compression:
#    enabled: false
#    mime-types: text/html,text/xml,text/plain,application/json,application/xml
#    min-response-size: 1KB

# 设置暴露所有端点
management:
  endpoints:
    web:
      exposure:
#        include: refresh
        include: "*"
    health:
      show-details: ALWAYS
#  security:
#    enabled: false