spring:
  application:
    name: stock

  redis:
    host: 111.229.53.45
    port: 6379
    password: Wbqsphr.1114redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
ribbon:
  ServerListRefreshInterval: 10
