spring:
  application:
    name: stock

  redis:
    host: 111.229.53.45
    port: 6379
    password: Wbqsphr.1114redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 600
  server:
    evictionIntervalTimerInMs: 4000
server:
  port: 8083
ribbon:
  ServerListRefreshInterval: 600000 #ribbon本地缓存更新时间
enable:
  refresh:
    eureka:
      local:
        cache: true
